src/ClickPoint/Models/Account/AddAccountViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ClickPoint.Models.Account
{
    public class AddAccountViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Verify Password")]
        [Compare("Password", ErrorMessage = "Passwords do not match.")]
        public string VerifyPassword { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [RegularExpression(".+@.+\\..+", ErrorMessage = "Email not valid.")]
        public string Email { get; set; }
    }
}

src/ClickPoint/Models/Account/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ClickPoint.Models.Account
{
    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }

        public bool HasLoginFailed { get; set; }

        public bool WasUserCreated { get; set; }
    }
}

src/ClickPoint/Controllers/AccountController.cs
using System.Linq;
using System.Web.Mvc;
using ClickPoint.Data;
using ClickPoint.Domain.Models;
using ClickPoint.Infrastructure;
using ClickPoint.Infrastructure.Authentication;
using ClickPoint.Models.Account;

namespace ClickPoint.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAuthenticator _authenticator;
        private readonly DataContext _dataContext;

        public AccountController(IAuthenticator authenticator, DataContext dataContext)
        {
            _authenticator = authenticator;
            _dataContext = dataContext;
        }

        public ActionResult Login(bool created = false)
        {
            var loginViewModel = new LoginViewModel
            {
                WasUserCreated = created
            };

            return View(loginViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!_authenticator.Verify(model.Username, model.Password))
            {
                model.HasLoginFailed = true;
                return View(model);
            }

            _authenticator.Authenticate(model.Username, model.Password);

            if (returnUrl.IsNullOrEmpty() || returnUrl == "/")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return Redirect(returnUrl);
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult LogOut()
        {
            _authenticator.Logout();

            return RedirectToAction("Login");
        }

        public ActionResult Add()
        {
            return View(new AddAccountViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AddAccountViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (_dataContext.Users.Any(u => u.UserName == model.Username))
            {
                ModelState.AddModelError("Username", "Username already taken. Please choose another.");
                return View(model);
            }

            if (_dataContext.Users.Any(u => u.Email == model.Email))
            {
                ModelState.AddModelError("Email", "User already exists for this Email. You should use the imaginary Forgot Your Password link.");
                return View(model);
            }

            var user = new User(model.Username, model.Email, model.FirstName, model.LastName);
            _dataContext.Users.Add(user);
            _dataContext.SaveChanges();

            _authenticator.CreateAccount(model.Username, model.Password);

            return RedirectToAction("Login", new { Created = true });
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Add(AddAccountViewModel model)
        //{
        //    var user = new User(model.Username, model.Email, model.FirstName, model.LastName);
        //    _dataContext.Users.Add(user);
        //    _dataContext.SaveChanges();

        //    return RedirectToAction("Login", new { Created = true });
        //}
    }
}

src/ClickPoint/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ClickPoint.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/ClickPoint/Controllers/LeadController.cs
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using ClickPoint.Data;
using ClickPoint.Domain.Models;
using ClickPoint.Infrastructure;
using ClickPoint.Infrastructure.Authentication;

namespace ClickPoint.Controllers
{
    [Authorize]
    public class LeadController : Controller
    {
        private readonly DataContext _dataContext;
        private readonly IAuthenticator _authenticator;

        public LeadController(DataContext dataContext, IAuthenticator authenticator)
        {
            _dataContext = dataContext;
            _authenticator = authenticator;
        }

        public ActionResult NewLead()
        {
            var currentUser = _authenticator.GetCurrentUser();

            Lead newLead;

            var scope = new TransactionScope(TransactionScopeOption.RequiresNew, new TransactionOptions { IsolationLevel = IsolationLevel.RepeatableRead });

            using (scope)
            {

                newLead = _dataContext.Leads
                                          .Where(lead => lead.Processor == null)
                                          .OrderBy(lead => lead.EnteredOn)
                                          .FirstOrDefault();

                if (newLead != null)
                {
                    newLead.Processor = currentUser;

                    _dataContext.SaveChanges();
                }

                scope.Complete();
            }

            if (newLead == null)
            {
                return Content("No new leads available.");
            }

            return Content("New Lead: {0} {1}".FormatWith(newLead.FirstName, newLead.LastName));
        }
    }
}

src/ClickPoint/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1>ClickPoint Lead Getter</h1>

<p class="text-center">
    @Html.ActionLink("Get Lead", "NewLead", "Lead", null, new { @class = "btn btn-primary btn-lg" })
</p>


<form method="POST" action="@Url.Action("LogOut", "Account")">
    <p class="text-center">
        <button type="submit" class="btn btn-info">Log Out</button>
    </p>
</form>

src/ClickPoint/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ClickPoint", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>